import type { Metadata } from "next";
import "./globals.css";
import { PrimeReactProvider } from "primereact/api";
// import "primereact/resources/theme/lara-light-cyan/theme.css"
import "primeicons/primeicons.css";
import { ToastProvider } from "@/utils/toast";
import ThemeScript from "./theme-script";
import ThemeProvider from "./theme-script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body>
        <ThemeProvider>
          <ToastProvider>
            <PrimeReactProvider>{children}</PrimeReactProvider>
          </ToastProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
